In [0]:
import torch

In [0]:
import torchvision

In [0]:
torch.cuda.is_available()

True

# Torch Tensors

In [0]:
# this is a 1-D Tensor
a = torch.tensor([2,2,1])

In [0]:
print(a)

tensor([2, 2, 1])


In [0]:
# this is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [0]:
# the size of the tensor
print(a.shape)

torch.Size([3])


In [0]:
print(b.shape)

torch.Size([4, 3])


In [0]:
print(a.size)

<built-in method size of Tensor object at 0x7faf7c9dc048>


In [0]:
print(b.size)

<built-in method size of Tensor object at 0x7faf7c9dc558>


In [0]:
# Get the height/numer of the rows of b
print(b.shape[0])

4


In [0]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [0]:
c2 = torch.tensor([2,2,1], dtype= torch.float)

In [0]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [0]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [0]:
d2 = torch.tensor([2,2,1], dtype=torch.double)

In [0]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [0]:
print(c2)
print(c2.dtype)

tensor([2., 2., 1.])
torch.float32


In [26]:
git status

SyntaxError: ignored

In [27]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
